### ISSUE TITLE
split Gizzverse Guide page into multiple pages

### ISSUE THREAD

**Issue by alxndr** [kglw-dot-net/site#13]
TBD — how to split up pages

**Comment by alxndr** [comment]
one page per entry in the Contents list?

* Strategies to get into KGATLW
* Band Biography
* (page for each Canonical album) x25
* (page for each Non-Canonical album) x15
* (page for each Bootleger release) x22
* The Murlocs
* What is the Gizzverse?
* About The Gizzverse Guide

**Comment by WBTGS95** [comment]
Here is some markdown for a landing page for kglw.net/gizzverse-guide

**Comment by WBTGS95** [comment]
# The Gizzverse Guide

How to get into King Gizzard and the Lizard Wizard? Many hear a small sample of this incredible band, but are immediately turned off when faced with what to listen to next out of such a high volume of material. Even experienced fans may not be familiar with every release, where each has a particular history and significance unique from the rest.  
This is the starting point of the Gizzverse Guide. Our catalogue of King Gizzard releases contains everything you need to get started, with introductory blurb for each release, objective information, and linkes that you can use to navigate to the next listening suggestion, based on what you already know or liked about the music.

If you have already heard an album and don’t know where to go from there, navigate to it from the the [releases](https://kglw.net/releases)  page.  
If you are completely new to the band, and don’t know where to start, check out some tips:

## Essentials

While always debatable, there is a path of ‘essential’ albums that most effectively show the core sounds, material, and stories that the band developed around. Many agree that [I’m in Your Mind Fuzz](https://kglw.net/releases/im-in-your-mind-fuzz/) is the first of these essential albums, and the solid epoch-point of the Gizzverse. These albums are thereafter referred to as the ‘Gizzverse albums’ in the prompts through the guide.

## Chronologically

Listening through a discography chronologically is the tried and true way of getting into a band, as it is the way that fans who have followed the band for the longest amount of time got to experience each release. While the sheer volume of albums may feel daunting, in most cases you can simply skip to the next release for a completely new sound or evolution.

Their first album is [12 Bar Bruise](https://kglw.net/releases/12-bar-bruise/); but if you have heard of the band by some of their newest material, then perhaps starting at the [current newest album](https://kglw.net/releases/changes/) and working backwards may work.

## Tone

Pick an album by title and cover. Each record has a distinct personality that is well conveyed in its title and artwork. [Murder of the Universe](https://kglw.net/releases/murder-of-the-universe/) is as dark and despondent as it looks and sounds, [Paper Mâché Dream Balloon](https://kglw.net/releases/paper-mache-dream-balloon/) as whimsical sounding as the scene on the front, so pick one that jumps out at you.

## Visuals

If something isn’t quite ‘clicking’, try some of the visual work as well. Personally, the [video for Rattlesnake](https://www.youtube.com/watch?v=Q-i1XZc8ZwA) is what instantly made me a fan after years of the band just being a funny name on the radio with an occasional stand out track. [Nonagon Infinity](https://kglw.net/releases/nonagon-infinity) and [Butterfly 3000](https://kglw.net/releases/butterfly-3000) are albums with lots of high quality visual work behind them.

The band have many great videos all available on their [Youtube Channel](https://www.youtube.com/playlist?list=PLjEpdah_kOgfhdncO5YfjdQY9hFzPq-2r).

## Playlists

You don’t need to experience each album all the way through right away. Some don’t have overarching concepts, and many are split into shorter suites or medleys. Some songs from different releases even belong together. Murder of the Nonagon Fuzz (re-upload) is an impressive fan made album mashup that uses only songs with accompanying music videos, seamlessly connecting five different projects.

Here are some playlist links:

[Enter the Gizzverse](https://www.youtube.com/watch?v=0rXwufFoJYw) (Spotify)  
[Heavy songs](https://open.spotify.com/playlist/7BfZwU7yVZrmX9XmwkJbaJ?si=54b411c741d24f7f) (Spotify)  
[Long songs](https://open.spotify.com/playlist/77cYJha9ttoOpZkZQOCid6?si=950dd84376a14818) (Spotify)  
[King Gizzard & the Lizard Wizard – Live In Brisbane ’21](https://www.youtube.com/playlist?list=PLjcIIEsozEvCSBYMVnGZsEbm31JfsKc2r) (Acoustic live set not available on DSPs)  
[King Gizzard & The Lizard Wizard – Gizzverse Odyssey](https://www.youtube.com/watch?v=3KIlzA7QO4I&list=WL&index=2&t=13s) (Digital only Official Bootlegger comp.)

## Criticism

While music critics and fan bases always clash, due credit for [Pitchfork](https://pitchfork.com/artists/32633-king-gizzard-the-lizard-wizard/) and Anthony Fantano at [The Needle Drop](https://www.youtube.com/playlist?list=PLW8qY_BtlPqcMWd3nn8E8p3rm3YlcFV0d) for (mostly) giving KGATLW a fair shot.

## Live Material

We are currently in a renaissance of KGATLW live performance, and the 2022 NA tour is what gathered together the fans that created this site. The band was just really starting to settle in as a ‘jam band’ with emphasis on their live show elevated to more than just promotion of their studio releases, when the COVID-19 pandemic paused live music touring for two years. Their several live in-studio performances at KEXP are known for drawing in fans:

[2015 – IIYMF/QRTRS](https://www.youtube.com/watch?v=4W19twyYD2Q)  
[2017 – FMB](https://www.youtube.com/watch?v=Qxxz7Tgfsv4)  
[2018 – MOTU (Live with crowd)](https://www.youtube.com/watch?v=G5Z4bma_tUM)  
[2018 – POLY/GS](https://www.youtube.com/watch?v=wxwu7FYFSek&t=1510s)  
[2019 – ITRN](https://www.youtube.com/watch?v=EnmFKS2eDBA)  
[2022 - IDPLMAL](https://www.youtube.com/watch?v=Jb8UMmrBlC8)  
However, there are many publications of KGATLW live material out there, from fan made crowd recordings, ‘[official bootlegger](https://boilerrhapsody.com/thegizzverseguide/?preview_id=947&preview_nonce=4340e51798&preview=true&_thumbnail_id=1003#Bootlegger)‘ band sanctioned soundboard recordings published by fans, and label published traditional [live show recordings](https://kglw.net/releases/live-in-san-francisco-2016).

## Other Guides

This is not the first or last dedicated guide for getting into King Gizzard.  
Album flowcharts are common in the fan base. Though clunky to use and constantly out of date, the idea retains an attractive simplicity. [Here](https://www.reddit.com/r/KGATLW/comments/lysvvz/i_finally_updated_my_king_gizzard_flowchart_now/) is the most common one.

[Get Into Gizz](https://get-into-gizz.com) is a simple, dedicated website.

Ball State Daily’s [choose your own adventure discography guide](https://www.ballstatedaily.com/byte/article/2021/02/choose-your-own-discography-guide-king-gizzard-the-lizard-wizard), is an (out of date) non-interactive written guide.

**Comment by alxndr** [comment]
To work in to a different page perhaps

## Related Artists & Projects
* Jason Galea (visual artist)
* [The Murlocs](/the-murlocs)
* Bullant
* Tropical Fuck Storm
* Mild High Club
* etc

**Comment by alxndr** [comment]
(running locally)
<img width="874" alt="Screen Shot 2022-11-17 at 10 35 46 PM" src="https://user-images.githubusercontent.com/174307/202637160-b913a0ed-be8b-4bbf-b65d-37a0a06dc5c6.png">

**Comment by alxndr** [comment]
working on this in the [`spike/zola` branch](https://github.com/kglw-dot-net/site/tree/spike/zola)

**Comment by alxndr** [comment]
done in soft launch https://alxndr.github.io/kglw-site/gizzverse-guide
